"""Source catalog for chess RAG ingestion."""

from __future__ import annotations

from typing import Any


GUTENBERG_BOOKS: list[dict[str, Any]] = [
    {
        "title": "Chess Fundamentals",
        "author": "Jose Raul Capablanca",
        "year": 1921,
        "url": "https://www.gutenberg.org/cache/epub/33870/pg33870.txt",
        "filename": "capablanca_chess_fundamentals.txt",
        "topics": ["opening", "middlegame", "endgame", "strategy", "fundamentals"],
        "level": "beginner-intermediate",
        "priority": 1,
        "type": "gutenberg",
    },
    {
        "title": "Chess Strategy",
        "author": "Edward Lasker",
        "year": 1915,
        "url": "https://www.gutenberg.org/cache/epub/5614/pg5614.txt",
        "filename": "edward_lasker_chess_strategy.txt",
        "topics": ["opening", "middlegame", "endgame", "strategy"],
        "level": "intermediate",
        "priority": 1,
        "type": "gutenberg",
    },
    {
        "title": "Chess and Checkers: The Way to Mastership",
        "author": "Edward Lasker",
        "year": 1918,
        "url": "https://www.gutenberg.org/cache/epub/4913/pg4913.txt",
        "filename": "edward_lasker_way_to_mastership.txt",
        "topics": ["fundamentals", "beginner_instruction"],
        "level": "beginner",
        "priority": 2,
        "type": "gutenberg",
    },
    {
        "title": "The Exploits and Triumphs of Paul Morphy",
        "author": "Frederick Milnes Edge",
        "year": 1859,
        "url": "https://www.gutenberg.org/cache/epub/34180/pg34180.txt",
        "filename": "morphy_exploits.txt",
        "topics": ["game_collection", "attacking_play", "tactics"],
        "level": "intermediate",
        "priority": 2,
        "type": "gutenberg",
    },
    {
        "title": "The Blue Book of Chess",
        "author": "Howard Staunton et al.",
        "year": 1895,
        "url": "https://www.gutenberg.org/cache/epub/30231/pg30231.txt",
        "filename": "blue_book_of_chess.txt",
        "topics": ["opening", "fundamentals", "instruction"],
        "level": "beginner",
        "priority": 3,
        "type": "gutenberg",
    },
    {
        "title": "Chess History and Reminiscences",
        "author": "H. E. Bird",
        "year": 1893,
        "url": "https://www.gutenberg.org/cache/epub/4902/pg4902.txt",
        "filename": "bird_chess_history.txt",
        "topics": ["history", "game_collection"],
        "level": "all",
        "priority": 3,
        "type": "gutenberg",
    },
    {
        "title": "The Adventure of Chess",
        "author": "Edward Lasker",
        "year": 1950,
        "url": "https://www.gutenberg.org/cache/epub/60228/pg60228.txt",
        "filename": "edward_lasker_adventure_of_chess.txt",
        "topics": ["history", "strategy", "instruction"],
        "level": "intermediate",
        "priority": 2,
        "type": "gutenberg",
    },
]


ARCHIVE_BOOKS: list[dict[str, Any]] = [
    {
        "title": "Lasker's Manual of Chess",
        "author": "Emanuel Lasker",
        "year": 1925,
        "archive_id": "laskersmanualofchess",
        "url": "https://archive.org/download/laskersmanualofchess/laskersmanualofchess_djvu.txt",
        "filename": "lasker_manual_of_chess.txt",
        "topics": ["complete_instruction", "strategy", "endgame", "philosophy"],
        "level": "intermediate-advanced",
        "priority": 1,
        "type": "archive",
        "notes": "Six-part masterwork: Elements, Open Games, End Games, Position Play, Combination Play, Aesthetic.",
    },
    {
        "title": "Common Sense in Chess",
        "author": "Emanuel Lasker",
        "year": 1896,
        "archive_id": "commonsenseinche00laskrich",
        "url": "https://archive.org/download/commonsenseinche00laskrich/commonsenseinche00laskrich_djvu.txt",
        "filename": "lasker_common_sense.txt",
        "topics": ["opening", "strategy", "fundamentals"],
        "level": "beginner-intermediate",
        "priority": 1,
        "type": "archive",
        "notes": "Based on 12 lectures to London chess club. Accessible and practical.",
    },
    {
        "title": "My System",
        "author": "Aron Nimzowitsch",
        "year": 1925,
        "archive_id": "nimzowitsch-my-system",
        "url": "https://archive.org/download/nimzowitsch-my-system/Nimzowitsch%20-%20My%20System.pdf",
        "filename": "nimzowitsch_my_system.txt",
        "topics": ["positional_play", "prophylaxis", "blockade", "pawn_structure", "overprotection"],
        "level": "intermediate-advanced",
        "priority": 1,
        "type": "archive",
        "notes": "Foundational positional text. PDF source (skip unless PDF extraction is enabled).",
        "format": "pdf",
    },
    {
        "title": "Chess Praxis",
        "author": "Aron Nimzowitsch",
        "year": 1929,
        "archive_id": "praxisofmysystem00nimz",
        "url": "https://archive.org/download/praxisofmysystem00nimz/praxisofmysystem00nimz_djvu.txt",
        "filename": "nimzowitsch_chess_praxis.txt",
        "topics": ["positional_play", "game_collection", "applied_strategy"],
        "level": "intermediate-advanced",
        "priority": 1,
        "type": "archive",
        "notes": "Annotated games applying My System ideas in practical play.",
    },
    {
        "title": "The Game of Chess",
        "author": "Siegbert Tarrasch",
        "year": 1931,
        "archive_id": "dli.ministry.13269",
        "url": "https://archive.org/download/dli.ministry.13269/dli.ministry.13269_djvu.txt",
        "filename": "tarrasch_game_of_chess.txt",
        "topics": ["complete_instruction", "strategy", "opening", "endgame"],
        "level": "intermediate",
        "priority": 1,
        "type": "archive",
        "notes": "Systematic textbook by the Praeceptor Germaniae.",
    },
    {
        "title": "Morphy's Games of Chess",
        "author": "Paul Morphy / J. Lowenthal",
        "year": 1898,
        "archive_id": "morphysgamesofch00morpiala",
        "url": "https://archive.org/download/morphysgamesofch00morpiala/morphysgamesofch00morpiala_djvu.txt",
        "filename": "morphy_games.txt",
        "topics": ["game_collection", "attacking_play", "tactics", "open_games"],
        "level": "intermediate",
        "priority": 2,
        "type": "archive",
        "notes": "Annotated games by one of the strongest attacking players in history.",
    },
    {
        "title": "The Chess-Player's Handbook",
        "author": "Howard Staunton",
        "year": 1847,
        "archive_id": "chessplayershan00staugoog",
        "url": "https://archive.org/download/chessplayershan00staugoog/chessplayershan00staugoog_djvu.txt",
        "filename": "staunton_handbook.txt",
        "topics": ["opening", "fundamentals", "instruction", "endgame"],
        "level": "beginner-intermediate",
        "priority": 2,
        "type": "archive",
        "notes": "Comprehensive opening and practical play reference.",
    },
    {
        "title": "My Best Games of Chess 1908-1923",
        "author": "Alexander Alekhine",
        "year": 1927,
        "archive_id": "mybestgamesofche00alek",
        "url": "https://archive.org/download/mybestgamesofche00alek/mybestgamesofche00alek_djvu.txt",
        "filename": "alekhine_best_games.txt",
        "topics": ["game_collection", "tactics", "attacking_play", "strategy"],
        "level": "advanced",
        "priority": 1,
        "type": "archive",
        "notes": "Deep annotations by the fourth world champion.",
    },
    {
        "title": "The Modern Chess Instructor",
        "author": "Wilhelm Steinitz",
        "year": 1889,
        "archive_id": "cu31924029919481",
        "url": "https://archive.org/download/cu31924029919481/cu31924029919481_djvu.txt",
        "filename": "steinitz_modern_instructor.txt",
        "topics": ["opening", "strategy", "positional_play"],
        "level": "intermediate-advanced",
        "priority": 2,
        "type": "archive",
        "notes": "Early codification of positional chess principles.",
    },
    {
        "title": "Analysis of the Game of Chess",
        "author": "Francois-Andre Danican Philidor",
        "year": 1749,
        "archive_id": "analysisgameche03philgoog",
        "url": "https://archive.org/download/analysisgameche03philgoog/analysisgameche03philgoog_djvu.txt",
        "filename": "philidor_analysis.txt",
        "topics": ["endgame", "pawn_play", "fundamentals"],
        "level": "intermediate",
        "priority": 2,
        "type": "archive",
        "notes": "Classic text introducing modern pawn-centric understanding.",
    },
    {
        "title": "The Hastings Chess Tournament 1895",
        "author": "Horace Cheshire (ed.)",
        "year": 1896,
        "archive_id": "cu31924029919820",
        "url": "https://archive.org/download/cu31924029919820/cu31924029919820_djvu.txt",
        "filename": "hastings_1895.txt",
        "topics": ["game_collection", "tournament_book", "tactics", "strategy"],
        "level": "intermediate-advanced",
        "priority": 2,
        "type": "archive",
        "notes": "Tournament book with dense annotated master games.",
    },
]


WIKI_SOURCES: list[dict[str, Any]] = [
    {
        "title": "Wikibooks: Chess Opening Theory",
        "author": "Wikibooks Contributors",
        "year": None,
        "type": "wikibooks",
        "base_url": "https://en.wikibooks.org/w/api.php",
        "category": "Chess_Opening_Theory",
        "filename_prefix": "wikibooks_openings",
        "topics": ["opening_theory"],
        "level": "all",
        "priority": 1,
        "notes": "Large category covering major openings and practical verbal plans.",
    },
    {
        "title": "Wikibooks: Chess Strategy",
        "author": "Wikibooks Contributors",
        "year": None,
        "type": "wikibooks",
        "base_url": "https://en.wikibooks.org/w/api.php",
        "category": "Chess_Strategy",
        "filename_prefix": "wikibooks_strategy",
        "topics": ["strategy", "positional_play"],
        "level": "all",
        "priority": 1,
    },
    {
        "title": "Wikipedia: Chess Openings",
        "author": "Wikipedia Contributors",
        "year": None,
        "type": "wikipedia",
        "base_url": "https://en.wikipedia.org/w/api.php",
        "category": "Chess_openings",
        "filename_prefix": "wiki_openings",
        "topics": ["opening_theory"],
        "level": "all",
        "priority": 2,
        "notes": "Category-based ingestion for named openings and variations.",
    },
    {
        "title": "Wikipedia: Chess Strategy and Tactics",
        "author": "Wikipedia Contributors",
        "year": None,
        "type": "wikipedia",
        "base_url": "https://en.wikipedia.org/w/api.php",
        "pages": [
            "Chess_strategy",
            "Chess_tactics",
            "Pawn_structure",
            "King_safety",
            "Isolated_pawn",
            "Passed_pawn",
            "Backward_pawn",
            "Doubled_pawns",
            "Pin_(chess)",
            "Fork_(chess)",
            "Skewer_(chess)",
            "Discovered_attack",
            "Zwischenzug",
            "Zugzwang",
            "Opposition_(chess)",
            "Outpost_(chess)",
            "Fianchetto",
            "Castling",
            "En_passant",
            "Promotion_(chess)",
            "Exchange_sacrifice",
            "Greek_gift_sacrifice",
            "Minority_attack",
            "Prophylaxis_(chess)",
            "Initiative_(chess)",
            "Compensation_(chess)",
            "Bishop_pair",
            "Good_bishop_and_bad_bishop",
            "Rook_on_the_seventh_rank",
            "Connected_passed_pawns",
            "Centralization_(chess)",
            "Open_file",
            "Semi-open_file",
            "Battery_(chess)",
            "Deflection_(chess)",
            "Decoy_(chess)",
            "Interference_(chess)",
            "Overloading_(chess)",
            "Windmill_(chess)",
            "X-ray_(chess)",
            "Clearance_(chess)",
            "Stalemate",
            "Checkmate",
            "Checkmate_pattern",
            "Smothered_mate",
            "Back-rank_checkmate",
            "Scholar%27s_mate",
            "Fool%27s_mate",
            "Lucena_position",
            "Philidor_position",
            "Rook_and_pawn_versus_rook_endgame",
            "Pawnless_chess_endgame",
            "King_and_pawn_versus_king_endgame",
            "Triangulation_(chess)",
            "Corresponding_squares",
            "Fortress_(chess)",
            "Tablebase",
        ],
        "filename_prefix": "wiki_concepts",
        "topics": ["strategy", "tactics", "endgame"],
        "level": "all",
        "priority": 1,
        "notes": "Focused concept pages for tactical motifs, strategy, and endgames.",
    },
]


NLP_DATASETS: list[dict[str, Any]] = [
    {
        "title": "Lichess Studies (Top Rated)",
        "author": "Lichess Community",
        "year": None,
        "type": "lichess_studies",
        "description": "Human-annotated chess studies exported as PGN with natural language comments.",
        "method": "GET https://lichess.org/api/study/{studyId}.pgn",
        "filename_prefix": "lichess_studies",
        "topics": ["all"],
        "level": "all",
        "priority": 1,
        "notes": "Curated studies are high-quality instructional text aligned to concrete positions.",
        "sample_study_ids": [
            "FoHVSPuM",
            "FY2FjVgN",
            "ByFy46Vz",
            "QCmetMJh",
        ],
    },
    {
        "title": "Lichess Puzzle Database",
        "author": "Lichess",
        "year": None,
        "type": "lichess_puzzles",
        "url": "https://database.lichess.org/lichess_db_puzzle.csv.zst",
        "description": "Millions of tactical puzzles with FEN, solution, rating, and themes.",
        "filename": "lichess_puzzles.csv",
        "topics": ["tactics"],
        "level": "all",
        "priority": 2,
        "notes": "Structured data; can be converted into natural-language tactical coaching templates.",
    },
]


def all_sources(include_pdf: bool = False) -> list[dict[str, Any]]:
    """Return all configured sources sorted by priority."""
    sources: list[dict[str, Any]] = []
    sources.extend(GUTENBERG_BOOKS)
    for source in ARCHIVE_BOOKS:
        if source.get("format") == "pdf" and not include_pdf:
            continue
        sources.append(source)
    sources.extend(WIKI_SOURCES)
    sources.extend(NLP_DATASETS)
    return sorted(sources, key=lambda item: int(item.get("priority", 99)))
